### PR TITLE
remove Guava dependency

### PR DESCRIPTION
**Pull request by janschaefer**
- one dependency less
- resulting jar file is 266k instead of 1.8M

### CODE REVIEW

**Comment by henryju** [comment]
http://jira.codehaus.org/browse/SONARPLUGINS-3871

**Comment by janschaefer** [comment]
Thanks for merging :-)

**Comment by daivanov** [comment]
Could you please release new version to Maven? Internal Guava was conflicting with projects using Guava of different versions.

**Comment by henryju** [comment]
@daivanov do you mean classloader of an Ant task is leaking into classpath of the built application? Is there no classloader isolation in Ant?

**Comment by daivanov** [comment]
No, when I execute sonar target, it runs application unit tests. Application uses Guava 0.18 and sonar-ant-task instead of using bundled Guava 0.11, finds and loads Guava 0.18, which causes a catastrophic failure, because API of Guava has changed between 0.11 and 0.18.

**Comment by henryju** [comment]
OK, I'll see if a release can be done.

**Pull request merged**
